/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainScreen;

import FileScroll.FileScroll;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.io.File;
import java.util.ArrayList;


/**
 *
 * @author 068684570
 */
public class MidScreen extends javax.swing.JPanel {

    /**
     * Creates new form MidScreen
     */
    ArrayList<File> files = new ArrayList();
    FileScroll fs = null;

    public MidScreen() {
        initComponents();
        files.add(new File("pic.png"));
        files.add(new File("pic2.png"));
        files.add(new File("text.txt"));
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (fs == null) {
            fs = new FileScroll(files, this, 100, 100);
        }
        fs.draw(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
